"""add_customer_status

Revision ID: 51a42eda6af5
Revises: 81b36c7ee3df
Create Date: 2026-07-16 12:15:52.752101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a42eda6af5'
down_revision: Union[str, Sequence[str], None] = '81b36c7ee3df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'status')
    # ### end Alembic commands ###
