"""add_undo_models

Revision ID: 59b8ce20a1b2
Revises: 51a42eda6af5
Create Date: 2026-07-16 13:13:23.356143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b8ce20a1b2'
down_revision: Union[str, Sequence[str], None] = '51a42eda6af5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('undo_points',
    sa.Column('operation_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_undo_points_id'), 'undo_points', ['id'], unique=False)
    op.create_table('undo_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('undo_point_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['undo_point_id'], ['undo_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_undo_logs_id'), 'undo_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_undo_logs_id'), table_name='undo_logs')
    op.drop_table('undo_logs')
    op.drop_index(op.f('ix_undo_points_id'), table_name='undo_points')
    op.drop_table('undo_points')
    # ### end Alembic commands ###
