"""add_dolibarr_fields

Revision ID: 81b36c7ee3df
Revises: e19379763eab
Create Date: 2026-07-16 11:11:57.103647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b36c7ee3df'
down_revision: Union[str, Sequence[str], None] = 'e19379763eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('barcode', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('vat_rate', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('status_buy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'status_buy')
    op.drop_column('products', 'status')
    op.drop_column('products', 'vat_rate')
    op.drop_column('products', 'barcode')
    op.drop_column('customers', 'special_code_3')
    op.drop_column('customers', 'special_code_2')
    op.drop_column('customers', 'special_code_1')
    op.drop_column('customers', 'sub_group_2')
    op.drop_column('customers', 'sub_group_1')
    op.drop_column('customers', 'group_name')
    op.drop_column('customers', 'customer_code')
    # ### end Alembic commands ###
