"""add_detailed_customer_fields

Revision ID: b7c54bd2d237
Revises: 59b8ce20a1b2
Create Date: 2026-07-16 13:32:14.703808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c54bd2d237'
down_revision: Union[str, Sequence[str], None] = '59b8ce20a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('authorized_person', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('nickname', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('phone2', sa.String(length=50), nullable=True))
    op.add_column('customers', sa.Column('phone_home', sa.String(length=50), nullable=True))
    op.add_column('customers', sa.Column('fax', sa.String(length=50), nullable=True))
    op.add_column('customers', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('address2', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('postcode', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('efatura_user', sa.String(length=50), nullable=True))
    op.add_column('customers', sa.Column('efatura_mailbox', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('record_date', sa.DateTime(), nullable=True))
    op.add_column('customers', sa.Column('photo_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'photo_path')
    op.drop_column('customers', 'record_date')
    op.drop_column('customers', 'notes')
    op.drop_column('customers', 'efatura_mailbox')
    op.drop_column('customers', 'efatura_user')
    op.drop_column('customers', 'region')
    op.drop_column('customers', 'postcode')
    op.drop_column('customers', 'country')
    op.drop_column('customers', 'district')
    op.drop_column('customers', 'city')
    op.drop_column('customers', 'address2')
    op.drop_column('customers', 'website')
    op.drop_column('customers', 'fax')
    op.drop_column('customers', 'phone_home')
    op.drop_column('customers', 'phone2')
    op.drop_column('customers', 'nickname')
    op.drop_column('customers', 'authorized_person')
    # ### end Alembic commands ###
